name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t testnginx

    - name: Run Nginx container
      run: docker run -d -p 80:80  testnginx

    - name: test nginx with curl
      run: |
          sudo apt-get install curl -y
          curl localhost | grep nginx
        
  secret:

    runs-on: ubuntu-latest
    
    steps:
    
      
    - name: testsecret
      run: echo  ${{ secrets.valeursecrete }}

      
